# 种子页面
seed:
  url: 'http://www.discuz.net/forum.php'
  # 解析器(forum,section,article)
  parser: 'forum'
# 选择器
selector:
  # 板块
  section: '.fl_g dt a'
  # 子版块
  sub_section: '.fl_tb .fl_g dl dt:nth-child(1) a'
  # 下一页按钮
  next_page: '.nxt'
  # 标题
  title: '.s.xst'
  # 文章
  article: 'div[id^=post_]:nth-child(3) td[id^=postmessage]'
# 请求头
header:
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
  Accept-Language: 'zh-CN,zh;q=0.9,en;q=0.8'
  DNT: '1'
  Host: 'www.discuz.net'
  Referer: 'https://www.discuz.net/'
  User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36'